import type { Metadata } from "next";
import Grid from "@mui/material/Grid";
import SnackBar from "@/util/SnackBar";

export const metadata: Metadata = {
  title: "Invoice Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): React.ReactNode {
  return (
    <Grid
      sx={{
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        width: "100%",
        height: "100%",
      }}
    >
      {children}
      <SnackBar />
    </Grid>
  );
}
