import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReduxProvider from "@/redux/ReduxProvider";
import "./globals.css";
import SnackBar from "@/util/SnackBar";
import Grid from "@mui/material/Grid2";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Invoice Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): React.ReactElement {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Grid container height={"100vh"} width={"100vw"}>
            {children}
          </Grid>
          <SnackBar />
        </ReduxProvider>
      </body>
    </html>
  );
}
